#!/usr/bin/env python3
"""Train the lightweight Chu Da Di move scorer used by NeuralAiStrategy.

The Android app keeps inference dependency-free, so this script trains the
same 23-input, 16-hidden-unit MLP offline and prints Kotlin arrays that can be
copied into NeuralMoveModel. It mixes broad synthetic states with self-play
states generated by a small Python implementation of the same card rules.
"""

from __future__ import annotations

import argparse
import hashlib
from itertools import combinations
import json
import math
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Tuple


FEATURE_COUNT = 23
HIDDEN_UNITS = 16
MODEL_VERSION = "mlp-selfplay-distilled-v3"
TRAINING_SEED = 20260610
DEFAULT_TRAIN_SIZE = 1800
DEFAULT_VALID_SIZE = 500
DEFAULT_SELF_PLAY_GAMES = 32
DEFAULT_VALID_SELF_PLAY_GAMES = 8
DEFAULT_EPOCHS = 140
DEFAULT_LR = 0.018
DEFAULT_WEIGHT_DECAY = 0.0002


Example = Tuple[List[float], float]
HandInfo = Tuple[int, int, int, Tuple[int, int]]
TrajectoryStep = Tuple[List[float], float, int]


@dataclass
class Model:
    hidden_weights: List[List[float]]
    hidden_bias: List[float]
    output_weights: List[float]
    output_bias: float

    @classmethod
    def initialized(cls, rng: random.Random) -> "Model":
        scale = 0.32
        return cls(
            hidden_weights=[
                [rng.uniform(-scale, scale) for _ in range(FEATURE_COUNT)]
                for _ in range(HIDDEN_UNITS)
            ],
            hidden_bias=[rng.uniform(-0.08, 0.08) for _ in range(HIDDEN_UNITS)],
            output_weights=[rng.uniform(-0.35, 0.35) for _ in range(HIDDEN_UNITS)],
            output_bias=0.0,
        )

    def predict(self, features: Sequence[float]) -> float:
        hidden = [
            math.tanh(dot(weights, features) + bias)
            for weights, bias in zip(self.hidden_weights, self.hidden_bias)
        ]
        return dot(self.output_weights, hidden) + self.output_bias


def dot(left: Sequence[float], right: Sequence[float]) -> float:
    return sum(a * b for a, b in zip(left, right))


def make_examples(count: int, rng: random.Random) -> List[Example]:
    return [make_example(rng) for _ in range(count)]


def make_example(rng: random.Random) -> Example:
    action_size_cards = rng.choices([1, 2, 3, 5], weights=[46, 18, 12, 24])[0]
    category_strength = category_for_action_size(action_size_cards, rng)
    hand_size_cards = rng.randint(action_size_cards, 13)
    remaining_cards = hand_size_cards - action_size_cards
    min_opponent_cards = rng.randint(1, 13)
    max_opponent_cards = rng.randint(min_opponent_cards, 13)
    pressure = max(0, 4 - min_opponent_cards)
    high_rank = rng.randint(0, 12)
    primary_rank = min(12, max(0, high_rank - rng.randint(0, 2)))
    high_suit = rng.randint(0, 3)
    is_five = 1.0 if action_size_cards == 5 else 0.0
    is_bomb = 1.0 if category_strength >= 7 else 0.0
    is_responding = 1.0 if rng.random() < 0.55 else 0.0
    responding_to_strong = 1.0 if is_responding and rng.random() < 0.28 else 0.0
    first_turn = 1.0 if rng.random() < 0.08 else 0.0
    pass_count = rng.randint(0, 3)
    break_penalty = rng.choices(range(0, 9), weights=[24, 22, 18, 12, 8, 6, 4, 3, 3])[0]
    low_share = rng.random() ** 0.7
    high_share = rng.random() ** 1.2
    group_potential = rng.random()
    run_potential = rng.random()
    bomb_enhanced = 1.0 if rng.random() < 0.5 else 0.0
    can_finish = 1.0 if remaining_cards == 0 else 0.0

    features = [
        action_size_cards / 5.0,
        category_strength / 8.0,
        primary_rank / 12.0,
        high_rank / 12.0,
        high_suit / 3.0,
        remaining_cards / 13.0,
        hand_size_cards / 13.0,
        min_opponent_cards / 13.0,
        max_opponent_cards / 13.0,
        pressure / 4.0,
        pass_count / 3.0,
        first_turn,
        is_responding,
        is_bomb,
        is_five,
        break_penalty / 8.0,
        low_share,
        high_share,
        group_potential,
        run_potential,
        bomb_enhanced,
        can_finish,
        responding_to_strong,
    ]
    return features, teacher_score(features)


def category_for_action_size(action_size_cards: int, rng: random.Random) -> int:
    if action_size_cards == 1:
        return 1
    if action_size_cards == 2:
        return 2
    if action_size_cards == 3:
        return 3
    return rng.choices([4, 5, 6, 7, 8], weights=[32, 18, 20, 14, 16])[0]


def teacher_score(features: Sequence[float]) -> float:
    action_size = features[0]
    category = features[1]
    primary_rank = features[2]
    high_rank = features[3]
    remaining = features[5]
    min_opponent = features[7]
    pressure = features[9]
    pass_count = features[10]
    first_turn = features[11]
    is_responding = features[12]
    is_bomb = features[13]
    is_five = features[14]
    breaks = features[15]
    low_share = features[16]
    high_share = features[17]
    group_potential = features[18]
    run_potential = features[19]
    bomb_enhanced = features[20]
    can_finish = features[21]
    responding_to_strong = features[22]

    score = 0.0
    score += can_finish * 7.5
    score += action_size * (2.2 + pressure * 2.0)
    score += category * (1.6 + is_responding * 0.4)
    score -= remaining * 4.6
    score -= breaks * 2.2
    score += low_share * 0.9
    score -= high_share * (0.9 - pressure * 0.35)
    score += group_potential * 1.15
    score += run_potential * 0.95
    score += is_five * 0.6
    score += pressure * (1.4 + (1.0 - min_opponent) * 0.5)
    score += pass_count * 0.2
    score -= high_rank * (0.45 if not responding_to_strong else 0.15)
    score -= primary_rank * 0.2
    score -= first_turn * high_share * 1.3

    bomb_penalty = 2.8 if can_finish == 0.0 else -1.2
    if responding_to_strong:
        bomb_penalty -= 2.1
    if bomb_enhanced:
        bomb_penalty -= 0.45
    score -= is_bomb * bomb_penalty

    return score / 2.5


def card_rank(card: int) -> int:
    return card % 13


def card_suit(card: int) -> int:
    return card // 13


def card_sort_key(card: int) -> Tuple[int, int]:
    return card_rank(card), card_suit(card)


def classify(cards: Sequence[int]) -> Optional[HandInfo]:
    sorted_cards = sorted(cards, key=card_sort_key)
    size = len(sorted_cards)
    if size == 0:
        return None
    if size == 1:
        card = sorted_cards[-1]
        return 1, card_rank(card), card, card_sort_key(card)
    ranks = [card_rank(card) for card in sorted_cards]
    if size == 2 and len(set(ranks)) == 1:
        card = sorted_cards[-1]
        return 2, ranks[0], card, card_sort_key(card)
    if size == 3 and len(set(ranks)) == 1:
        card = sorted_cards[-1]
        return 3, ranks[0], card, card_sort_key(card)
    if size != 5:
        return None

    rank_counts = {rank: ranks.count(rank) for rank in set(ranks)}
    suits = {card_suit(card) for card in sorted_cards}
    distinct_ranks = sorted(rank_counts)
    is_flush = len(suits) == 1
    is_straight = (
        len(distinct_ranks) == 5
        and 12 not in distinct_ranks
        and all(b == a + 1 for a, b in zip(distinct_ranks, distinct_ranks[1:]))
    )
    high_card = sorted_cards[-1]
    high_key = card_sort_key(high_card)
    if is_straight and is_flush:
        return 8, max(distinct_ranks), high_card, high_key
    if 4 in rank_counts.values():
        primary = next(rank for rank, count in rank_counts.items() if count == 4)
        return 7, primary, high_card, high_key
    if sorted(rank_counts.values()) == [2, 3]:
        primary = next(rank for rank, count in rank_counts.items() if count == 3)
        return 6, primary, high_card, high_key
    if is_flush:
        return 5, card_rank(high_card), high_card, high_key
    if is_straight:
        return 4, max(distinct_ranks), high_card, high_key
    return None


def is_bomb(info: Optional[HandInfo]) -> bool:
    return info is not None and info[0] in (7, 8)


def can_beat(previous: HandInfo, next_hand: HandInfo, bomb_enhanced: bool = True) -> bool:
    previous_category = previous[0]
    next_category = next_hand[0]
    if previous_category == next_category:
        if next_hand[1] != previous[1]:
            return next_hand[1] > previous[1]
        return next_hand[3] > previous[3]
    if bomb_enhanced and is_bomb(next_hand) and not is_bomb(previous):
        return True
    previous_is_five = previous_category >= 4
    next_is_five = next_category >= 4
    return previous_is_five and next_is_five and next_category > previous_category


def standard_deck() -> List[int]:
    return [suit * 13 + rank for suit in range(4) for rank in range(13)]


def deal(rng: random.Random) -> List[List[int]]:
    deck = standard_deck()
    rng.shuffle(deck)
    return [sorted(deck[index * 13 : (index + 1) * 13], key=card_sort_key) for index in range(4)]


def remove_cards(hand: Sequence[int], cards: Sequence[int]) -> List[int]:
    selected = set(cards)
    return [card for card in hand if card not in selected]


def legal_plays(hands: Sequence[Sequence[int]], current_player: int, last_hand: Optional[HandInfo], first_turn: bool) -> List[List[int]]:
    first_card = 3 * 13
    hand = hands[current_player]
    plays: List[List[int]] = []
    for size in (1, 2, 3, 5):
        if size > len(hand):
            continue
        for raw_cards in combinations(hand, size):
            cards = list(raw_cards)
            info = classify(cards)
            if info is None:
                continue
            if last_hand is None:
                if first_turn and first_card not in cards:
                    continue
            elif not can_beat(last_hand, info):
                continue
            plays.append(cards)
    return sorted(plays, key=lambda cards: (len(cards), card_sort_key(max(cards, key=card_sort_key))))


def break_penalty(hand: Sequence[int], cards: Sequence[int]) -> int:
    ranks = [card_rank(card) for card in hand]
    return sum(ranks.count(card_rank(card)) if ranks.count(card_rank(card)) >= 2 else 0 for card in cards)


def group_potential(cards: Sequence[int]) -> float:
    if not cards:
        return 1.0
    ranks = [card_rank(card) for card in cards]
    score = 0.0
    for rank in set(ranks):
        count = ranks.count(rank)
        if count == 2:
            score += 1.0
        elif count == 3:
            score += 1.8
        elif count >= 4:
            score += 2.5
    return min(1.0, max(0.0, score / 8.0))


def run_potential(cards: Sequence[int]) -> float:
    if len(cards) < 5:
        return 0.0
    ranks = sorted({card_rank(card) for card in cards})
    best = 1
    current = 1
    for previous, rank in zip(ranks, ranks[1:]):
        current = current + 1 if rank == previous + 1 else 1
        best = max(best, current)
    return min(1.0, max(0.0, best / 5.0))


def encode_self_play_features(
    hands: Sequence[Sequence[int]],
    current_player: int,
    last_hand: Optional[HandInfo],
    pass_count: int,
    first_turn: bool,
    cards: Sequence[int],
    bomb_enhanced: bool = True,
) -> List[float]:
    hand = list(hands[current_player])
    info = classify(cards)
    remaining = remove_cards(hand, cards)
    opponent_sizes = [len(other_hand) for index, other_hand in enumerate(hands) if index != current_player]
    min_opponent_cards = min(opponent_sizes)
    max_opponent_cards = max(opponent_sizes)
    action_size_cards = max(1, len(cards))
    high_card = max(cards, key=card_sort_key)
    high_rank = card_rank(high_card)
    high_suit = card_suit(high_card)
    category_strength = info[0] if info is not None else 0
    primary_rank = info[1] if info is not None else high_rank
    responding_to_strong = 1.0 if last_hand is not None and last_hand[0] >= 6 else 0.0

    return [
        action_size_cards / 5.0,
        category_strength / 8.0,
        primary_rank / 12.0,
        high_rank / 12.0,
        high_suit / 3.0,
        len(remaining) / 13.0,
        len(hand) / 13.0,
        min_opponent_cards / 13.0,
        max_opponent_cards / 13.0,
        max(0, 4 - min_opponent_cards) / 4.0,
        pass_count / 3.0,
        1.0 if first_turn else 0.0,
        1.0 if last_hand is not None else 0.0,
        1.0 if is_bomb(info) else 0.0,
        1.0 if len(cards) == 5 else 0.0,
        break_penalty(hand, cards) / 8.0,
        sum(1 for card in cards if card_rank(card) <= 4) / float(action_size_cards),
        sum(1 for card in cards if card_rank(card) >= 10) / float(action_size_cards),
        group_potential(remaining),
        run_potential(remaining),
        1.0 if bomb_enhanced else 0.0,
        1.0 if not remaining else 0.0,
        responding_to_strong,
    ]


def state_value_after_play(hands: Sequence[Sequence[int]], current_player: int, cards: Sequence[int]) -> float:
    remaining = len(hands[current_player]) - len(cards)
    if remaining == 0:
        return 2.4
    opponent_min = min(len(hand) for index, hand in enumerate(hands) if index != current_player)
    pressure = max(0, 4 - opponent_min)
    return (13 - remaining) * 0.045 + pressure * 0.12 - remaining * 0.055


def candidate_target(hands: Sequence[Sequence[int]], current_player: int, features: Sequence[float], cards: Sequence[int]) -> float:
    return teacher_score(features) + state_value_after_play(hands, current_player, cards) * 0.55


def choose_self_play_move(scored: Sequence[Tuple[List[int], List[float], float]], rng: random.Random, exploration: float) -> Tuple[List[int], List[float], float]:
    return max(scored, key=lambda item: item[2] + rng.uniform(-exploration, exploration))


def make_self_play_examples(
    game_count: int,
    rng: random.Random,
    max_turns: int = 240,
    max_examples_per_state: int = 7,
    exploration: float = 0.22,
) -> List[Example]:
    examples: List[Example] = []
    for _ in range(game_count):
        hands = deal(rng)
        current_player = next(index for index, hand in enumerate(hands) if 3 * 13 in hand)
        last_hand: Optional[HandInfo] = None
        last_player: Optional[int] = None
        pass_count = 0
        first_turn = True
        trajectory: List[TrajectoryStep] = []
        winner: Optional[int] = None

        for _turn in range(max_turns):
            legal = legal_plays(hands, current_player, last_hand, first_turn)
            if not legal:
                if last_player is None:
                    break
                pass_count += 1
                if pass_count >= 3:
                    current_player = last_player
                    last_hand = None
                    pass_count = 0
                    first_turn = False
                else:
                    current_player = (current_player + 1) % 4
                continue

            scored = []
            for cards in legal:
                features = encode_self_play_features(hands, current_player, last_hand, pass_count, first_turn, cards)
                target = candidate_target(hands, current_player, features, cards)
                scored.append((cards, features, target))

            scored_by_target = sorted(scored, key=lambda item: item[2], reverse=True)
            selected_examples = scored_by_target[:max_examples_per_state]
            if len(scored_by_target) > max_examples_per_state:
                selected_examples += rng.sample(scored_by_target[max_examples_per_state:], k=min(2, len(scored_by_target) - max_examples_per_state))
            examples.extend((features, target) for _cards, features, target in selected_examples)

            chosen_cards, chosen_features, chosen_target = choose_self_play_move(scored, rng, exploration)
            trajectory.append((chosen_features, chosen_target, current_player))
            hand_info = classify(chosen_cards)
            hands[current_player] = remove_cards(hands[current_player], chosen_cards)
            if not hands[current_player]:
                winner = current_player
                break
            last_hand = hand_info
            last_player = current_player
            pass_count = 0
            first_turn = False
            current_player = (current_player + 1) % 4

        if winner is not None:
            for features, target, player_id in trajectory:
                outcome = 1.4 if player_id == winner else -0.45
                examples.append((features, target + outcome))
    return examples


def train(model: Model, data: List[Example], epochs: int, lr: float, weight_decay: float, rng: random.Random) -> None:
    for epoch in range(epochs):
        rng.shuffle(data)
        progress = epoch / max(1, epochs - 1)
        step_size = lr * (1.0 - 0.65 * progress)
        for features, target in data:
            hidden_pre = [
                dot(weights, features) + bias
                for weights, bias in zip(model.hidden_weights, model.hidden_bias)
            ]
            hidden = [math.tanh(value) for value in hidden_pre]
            prediction = dot(model.output_weights, hidden) + model.output_bias
            error = prediction - target

            output_weights_before = model.output_weights[:]
            for unit in range(HIDDEN_UNITS):
                gradient = error * hidden[unit] + weight_decay * model.output_weights[unit]
                model.output_weights[unit] -= step_size * gradient
            model.output_bias -= step_size * error

            for unit in range(HIDDEN_UNITS):
                hidden_gradient = error * output_weights_before[unit] * (1.0 - hidden[unit] * hidden[unit])
                row = model.hidden_weights[unit]
                for index in range(FEATURE_COUNT):
                    gradient = hidden_gradient * features[index] + weight_decay * row[index]
                    row[index] -= step_size * gradient
                model.hidden_bias[unit] -= step_size * hidden_gradient


def metrics(model: Model, data: Iterable[Example]) -> Tuple[float, float]:
    total_squared = 0.0
    total_absolute = 0.0
    count = 0
    for features, target in data:
        error = model.predict(features) - target
        total_squared += error * error
        total_absolute += abs(error)
        count += 1
    return total_squared / count, total_absolute / count


def format_array(values: Sequence[float]) -> str:
    return "doubleArrayOf(" + ", ".join(f"{value:.6f}" for value in values) + ")"


def weight_checksum(model: Model) -> str:
    payload = {
        "hiddenWeights": [[f"{value:.6f}" for value in row] for row in model.hidden_weights],
        "hiddenBias": [f"{value:.6f}" for value in model.hidden_bias],
        "outputWeights": [f"{value:.6f}" for value in model.output_weights],
        "outputBias": f"{model.output_bias:.6f}",
    }
    encoded = json.dumps(payload, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def print_kotlin(model: Model) -> None:
    print("private val hiddenWeights = arrayOf(")
    for index, row in enumerate(model.hidden_weights):
        suffix = "," if index < len(model.hidden_weights) - 1 else ""
        print(f"    {format_array(row)}{suffix}")
    print(")")
    print()
    print(f"private val hiddenBias = {format_array(model.hidden_bias)}")
    print()
    print(f"private val outputWeights = {format_array(model.output_weights)}")
    print(f"private const val OUTPUT_BIAS = {model.output_bias:.6f}")
    print(f'const val WEIGHT_CHECKSUM = "{weight_checksum(model)}"')


def write_manifest(
    path: Path,
    train_size: int,
    valid_size: int,
    self_play_train_size: int,
    self_play_valid_size: int,
    args: argparse.Namespace,
    initial_loss: float,
    initial_mae: float,
    final_loss: float,
    final_mae: float,
    model: Model,
) -> None:
    manifest = {
        "modelVersion": MODEL_VERSION,
        "weightChecksum": weight_checksum(model),
        "featureCount": FEATURE_COUNT,
        "hiddenUnits": HIDDEN_UNITS,
        "parameterCount": FEATURE_COUNT * HIDDEN_UNITS + HIDDEN_UNITS + HIDDEN_UNITS + 1,
        "seed": args.seed,
        "training": {
            "syntheticTrain": args.train_size,
            "selfPlayGames": args.self_play_games,
            "selfPlayTrain": self_play_train_size,
            "totalTrain": train_size,
            "epochs": args.epochs,
            "learningRate": args.lr,
            "weightDecay": args.weight_decay,
        },
        "validation": {
            "syntheticValid": args.valid_size,
            "selfPlayGames": args.valid_self_play_games,
            "selfPlayValid": self_play_valid_size,
            "totalValid": valid_size,
        },
        "metrics": {
            "initialMse": round(initial_loss, 6),
            "initialMae": round(initial_mae, 6),
            "finalMse": round(final_loss, 6),
            "finalMae": round(final_mae, 6),
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--train-size", type=int, default=DEFAULT_TRAIN_SIZE)
    parser.add_argument("--valid-size", type=int, default=DEFAULT_VALID_SIZE)
    parser.add_argument("--self-play-games", type=int, default=DEFAULT_SELF_PLAY_GAMES)
    parser.add_argument("--valid-self-play-games", type=int, default=DEFAULT_VALID_SELF_PLAY_GAMES)
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS)
    parser.add_argument("--lr", type=float, default=DEFAULT_LR)
    parser.add_argument("--weight-decay", type=float, default=DEFAULT_WEIGHT_DECAY)
    parser.add_argument("--seed", type=int, default=TRAINING_SEED)
    parser.add_argument("--kotlin-only", action="store_true")
    parser.add_argument("--manifest", type=Path)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    train_data = make_examples(args.train_size, rng)
    train_self_play = make_self_play_examples(args.self_play_games, rng)
    train_data.extend(train_self_play)
    valid_data = make_examples(args.valid_size, rng)
    valid_self_play = make_self_play_examples(args.valid_self_play_games, rng)
    valid_data.extend(valid_self_play)
    model = Model.initialized(rng)
    initial_loss, initial_mae = metrics(model, valid_data)
    train(model, train_data, args.epochs, args.lr, args.weight_decay, rng)
    final_loss, final_mae = metrics(model, valid_data)
    if args.manifest is not None:
        write_manifest(
            args.manifest,
            train_size=len(train_data),
            valid_size=len(valid_data),
            self_play_train_size=len(train_self_play),
            self_play_valid_size=len(valid_self_play),
            args=args,
            initial_loss=initial_loss,
            initial_mae=initial_mae,
            final_loss=final_loss,
            final_mae=final_mae,
            model=model,
        )

    if not args.kotlin_only:
        print(f"seed={args.seed}")
        print(
            f"train_size={len(train_data)} synthetic_train={args.train_size} "
            f"self_play_train={len(train_self_play)}"
        )
        print(
            f"valid_size={len(valid_data)} synthetic_valid={args.valid_size} "
            f"self_play_valid={len(valid_self_play)} epochs={args.epochs}"
        )
        print(f"initial_mse={initial_loss:.6f} initial_mae={initial_mae:.6f}")
        print(f"final_mse={final_loss:.6f} final_mae={final_mae:.6f}")
        print()
    print_kotlin(model)


if __name__ == "__main__":
    main()
